# Generated by Django 4.0.1 on 2022-01-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_rename_id_restaurant_table_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='nincidents',
        ),
    ]
