# Generated by Django 4.0.1 on 2022-01-28 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_id', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='users.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(editable=False, max_length=36, unique=True, verbose_name='uuid'),
        ),
    ]
