# Generated by Django 4.0.1 on 2022-01-25 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_restaurant_nincidents'),
        ('users', '0002_alter_incident_id_restaurant_alter_incident_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='id_restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_restaurant_id', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_user_id', to='users.user'),
        ),
    ]
