# Generated by Django 4.0.1 on 2022-02-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='types',
            field=models.CharField(blank=True, max_length=10, verbose_name='types'),
        ),
    ]
